name: Release Pre-Built packages

# Controls when the action will run.
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x

    # Runs a single command using the runners shell
    - name: Build the packages
      run: |
        cd build
        pwsh build.ps1
    
    # Upload packages to the release
    - name: Upload to Release
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: build/packages/lm-client-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
