name: Upload pre-built packages to release

# Controls when the action will run.
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Packages
    
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check-out
      uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x

    # Runs a single command using the runners shell
    - name: Build the packages
      run: |
        cd build
        pwsh build.ps1
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-packages
        path: build/packages/

  upload:
    name: Upload packages to Release
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: built-packages

    # Upload packages to the release
    - name: Upload to Release - Win-x64
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: lm-client-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload to Release - Win-x86
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: lm-client-win-x86.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload to Release - Linux-x64
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: lm-client-linux-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
