name: Upload pre-built packages to release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: win

    name: Build Packages for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x

      - name: Build the packages
        run: |
          cd build
          pwsh build.ps1 ${{ matrix.target }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-packages-${{ matrix.target }}
          path: build/packages/

  upload:
    strategy:
      matrix:
        target: [win, linux]
        arch: [x86, x64]
        include:
          - target: win
            ext: zip
            mime: application/zip
          - target: linux
            ext: tar.gz
            mime: application/gzip

    name: Upload ${{ matrix.target }}-${{ matrix.arch }} to Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download Build Artifacts ${{ matrix.target }}
        uses: actions/download-artifact@v2
        with:
          name: built-packages-${{ matrix.target }}

      - name: Upload to Release - ${{ matrix.target }}-${{ matrix.arch }}
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          args: lm-client-${{ matrix.target }}-${{ matrix.arch }}.${{ matrix.ext }} ${{ matrix.mime }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
